### ISSUE TITLE
Strange return

### ISSUE THREAD

**Issue by arj03** [dominictarr/flumelog-aligned-offset#4]
Was looking at a wierd case and found [this](https://github.com/dominictarr/flumelog-aligned-offset/blob/master/frame.js#L59) line strange. Shouldn't that be return 0?

**Comment by dominictarr** [comment]
the code could definitely be nicer, but the stream code checks for undefined result https://github.com/dominictarr/flumelog-aligned-offset/blob/master/stream.js#L139

so that will end the stream.

The proper signal would be -1 I think, like a completely empty flumelog has -1 for the sequence. zero is the offset of the first item (in some log formats)

**Comment by dominictarr** [comment]
If I recall, I did this streams code quite a guardrail programming style. (i.e. crash into the tests, change things until they pass etc)

**Comment by arj03** [comment]
Yes. Makes sense. Thanks
